name: Download inflation from INDEC

on:
  schedule:
    - cron: '40 19 11-16 * *'
  workflow_dispatch:

jobs:
  download-inflation:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v4

    - name: Check weekend
      id: check_weekend
      run: |
        weekday=$(date +%u)  # 1=Monday, ..., 7=Sunday
        echo "Weekday number: $weekday"
        if [ "$weekday" -eq 6 ] || [ "$weekday" -eq 7 ]; then
          echo "is_weekend=true" >> $GITHUB_OUTPUT
        else
          echo "is_weekend=false" >> $GITHUB_OUTPUT
        fi

    - name: Set up R
      if: steps.check_weekend.outputs.is_weekend == 'false'
      uses: r-lib/actions/setup-r@v2

    - name: Install R packages
      if: steps.check_weekend.outputs.is_weekend == 'false'
      run: |
        Rscript -e 'install.packages(c("lubridate", "readxl"))'

    - name: Run script
      if: steps.check_weekend.outputs.is_weekend == 'false'
      run: |
        Rscript download_inflation.R

    - name: Check for changes
      if: steps.check_weekend.outputs.is_weekend == 'false'
      run: |
        git config user.name "github-actions"
        git config user.email "github-actions@github.com"

        if git diff --quiet inflation_data.csv; then
          echo "No changes to inflation_data.csv"
        else
          prev_month=$(date -d "$(date +%Y-%m-01) -1 month" +%B)
          git add inflation_data.csv
          git commit -m "Add ${prev_month} inflation data"
          git push
        fi
