name: INDEC download

on:
  schedule:
    - cron: '40 19 11-16 * *'
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write

jobs:
  download-inflation:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v4

    - name: Check weekend
      id: check_weekend
      run: |
        weekday=$(date +%u)  # 1=Monday, ..., 7=Sunday
        echo "Weekday number: $weekday"
        if [ "$weekday" -eq 6 ] || [ "$weekday" -eq 7 ]; then
          echo "is_weekend=true" >> $GITHUB_OUTPUT
        else
          echo "is_weekend=false" >> $GITHUB_OUTPUT
        fi
    
    - name: Install GitHub CLI
      if: steps.check_weekend.outputs.is_weekend == 'false'
      run: |
          sudo apt-get update
          sudo apt-get install gh -y

    - name: Set up R
      if: steps.check_weekend.outputs.is_weekend == 'false'
      uses: r-lib/actions/setup-r@v2

    - name: Install R packages
      if: steps.check_weekend.outputs.is_weekend == 'false'
      run: |
        Rscript -e 'install.packages(c("lubridate", "readxl"))'

    - name: Run script
      if: steps.check_weekend.outputs.is_weekend == 'false'
      run: |
        Rscript download_inflation.R
    
    - name: Get previous month
      if: steps.check_weekend.outputs.is_weekend == 'false'
      id: set_prev_month
      run: |
        prev_month=$(date -d "$(date +%Y-%m-01) -1 month" +%B)
        echo "prev_month=$prev_month"
        echo "prev_month=$prev_month" >> $GITHUB_OUTPUT
        
    - name: Commit and push to new branch
      if: steps.check_weekend.outputs.is_weekend == 'false'
      env:
        GH_TOKEN: ${{ secrets.PAT_GITHUB }}
      run: |
        git config user.name "github-actions"
        git config user.email "github-actions@github.com"

        if git diff --quiet inflation_data.csv; then
          echo "No changes to inflation_data.csv"
          exit 0
        fi

        BRANCH="auto/inflation-update"
        git checkout -b "$BRANCH"
        git add inflation_data.csv
        git commit -m "Add ${{ steps.set_prev_month.outputs.prev_month }} inflation data"
        git push -f origin "$BRANCH"

        PR_TITLE="Update: ${{ steps.set_prev_month.outputs.prev_month }} inflation data"
        PR_BODY="Auto-generated update by the download_inflation workflow."

        # Check if PR already exists
        existing_pr=$(gh pr list --head "$BRANCH" --json number -q '.[0].number')

        if [ -z "$existing_pr" ]; then
          gh pr create --title "$PR_TITLE" --body "$PR_BODY" --head "$BRANCH" --base main
        else
          echo "PR already exists: #$existing_pr"
        fi
        
    - name: Trigger PR check via empty commit
      if: steps.check_weekend.outputs.is_weekend == 'false'
      run: |
        git config user.name "github-actions"
        git config user.email "github-actions@github.com"
        git commit --allow-empty -m "Trigger format-check"
        git push origin auto/inflation-update
