# Workflow derived from https://github.com/posit-dev/setup-air/tree/main/examples
name: Air format

on:
  pull_request:
  push:
  workflow_dispatch:

permissions: read-all

jobs:
  format-check:
    name: format-check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install
        uses: posit-dev/setup-air@v1
        with:
          version: "0.5.0"

      - name: Print Air version
        run: air --version

      - name: Check
        run: air format . --check
        