# Workflow derived from https://github.com/posit-dev/setup-air/tree/main/examples
name: Air format

on:
  push:
    branches: [main]
  workflow_dispatch:
  pull_request:
  #pull_request_target:
    #types: [opened, synchronize, reopened]

permissions: read-all

jobs:
  format-check:
    name: format-check
    if: github.event_name == 'pull_request' || (github.event_name == 'pull_request_target' && github.event.pull_request.head.repo.full_name != github.repository)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install
        uses: posit-dev/setup-air@v1
        with:
          version: "0.5.0"

      - name: Print Air version
        run: air --version

      - name: Check
        run: air format . --check